base_lr: 0.001
batch_size: 32
best_cnet: null
best_rnet: null
bps_size: 4096
c_weights_path: /grabnet/configs/rhand_weight.npy
cuda_id: 0
dataset_dir: grab_unzip_data/data
expr_ID: V01
faces_path: /grabnet/configs/faces.npy
kl_coef: 0.005
latentD: 10
load_on_ram: false
log_every_epoch: 1
n_epochs: 200
n_neurons: 512
n_workers: 2
reg_coef: 0.0005
rhm_path: ManoHand/
seed: 4815
try_num: 22
use_multigpu: false
vpe_path: /grabnet/configs/verts_per_edge.npy
work_dir: grabnet/configs
